

CREATE TABLE USERS(
USERID INT PRIMARY KEY IDENTITY,
USERNAME NVARCHAR(100) NOT NULL,
USERPASS NVARCHAR(100) NOT NULL,
EMAIL NVARCHAR(100) NOT NULL,
USER_PHONE NVARCHAR(100)
);

delete from USERS;
INSERT INTO USERS(USERNAME, USERPASS, EMAIL, USER_PHONE)
VALUES ('MAHEEN', '123', 'WWW', '031267221');

DELETE FROM USERS;

DBCC CHECKIDENT ('USERS', RESEED, 0);  -- Resets the identity to 0, so the next insert will use 1

INSERT INTO USERS(USERNAME, USERPASS, EMAIL, USER_PHONE)
VALUES ('MAHEEN', '123', 'WWW', '031267221');

INSERT INTO USERS(USERNAME, USERPASS, EMAIL, USER_PHONE)
VALUES ('HIRA', '111', 'hhh', '0312747272');

INSERT INTO USERS(USERNAME, USERPASS, EMAIL, USER_PHONE)
VALUES ('WANIYA', '222', 'www.waniyakhan20002@gmail.com', '0312747272');



INSERT INTO USERS(USERNAME, USERPASS, EMAIL, USER_PHONE)
VALUES ('WANI', '20002', 'waniyakhan443@gmail.com', '091275736');
SELECT * FROM USERS;



